"""empty message

Revision ID: 1cab3aea5448
Revises: 4b159c0af198
Create Date: 2022-05-07 14:32:52.662864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cab3aea5448'
down_revision = '4b159c0af198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('teachers', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'about_me')
    op.drop_column('student', 'about_me')
    # ### end Alembic commands ###
