"""empty message

Revision ID: 4a66743ae3bd
Revises: aadd1d9c6b5a
Create Date: 2022-05-08 17:12:27.644957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a66743ae3bd'
down_revision = 'aadd1d9c6b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('students', sa.Column('studentclass_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'studentclasses', ['studentclass_id'], ['id'])
    op.drop_column('students', 'student_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('student_class', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'studentclass_id')
    op.drop_table('studentclasses')
    # ### end Alembic commands ###
