"""empty message

Revision ID: 4b159c0af198
Revises: 94ec8b0c5811
Create Date: 2022-05-06 16:24:10.159623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b159c0af198'
down_revision = '94ec8b0c5811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column('teachers', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teachers', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'teachers', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_column('teachers', 'department_id')
    op.drop_column('teachers', 'course_id')
    # ### end Alembic commands ###
