"""empty message

Revision ID: 5ff388071190
Revises: 
Create Date: 2022-05-04 18:06:33.216763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff388071190'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reg_date', sa.String(length=80), nullable=True),
    sa.Column('course', sa.String(length=80), nullable=True),
    sa.Column('mobile_no', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('admission_no', sa.String(length=80), nullable=True),
    sa.Column('birth_date', sa.String(length=80), nullable=True),
    sa.Column('student_id', sa.String(length=80), nullable=True),
    sa.Column('student_class', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('religion', sa.String(length=80), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('father_name', sa.String(length=80), nullable=True),
    sa.Column('mother_name', sa.String(length=80), nullable=True),
    sa.Column('father_occ', sa.String(length=80), nullable=True),
    sa.Column('mother_occ', sa.String(length=80), nullable=True),
    sa.Column('father_email', sa.String(length=80), nullable=True),
    sa.Column('mother_email', sa.String(length=80), nullable=True),
    sa.Column('father_mobile_no', sa.String(length=80), nullable=True),
    sa.Column('mother_mobile_no', sa.String(length=80), nullable=True),
    sa.Column('present_add', sa.Text(), nullable=True),
    sa.Column('permanent_add', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_student_id'), 'student', ['student_id'], unique=False)
    op.add_column('users', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    op.drop_index(op.f('ix_student_student_id'), table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###
