"""empty message

Revision ID: 67401b87d112
Revises: 2b0e71e806cf
Create Date: 2022-05-08 14:21:15.745270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67401b87d112'
down_revision = '2b0e71e806cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'fees')
    # ### end Alembic commands ###
