"""empty message

Revision ID: 85306045cbc4
Revises: 9cbf88569489
Create Date: 2022-05-05 19:44:16.270750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85306045cbc4'
down_revision = '9cbf88569489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
