"""empty message

Revision ID: 94ec8b0c5811
Revises: 
Create Date: 2022-05-06 16:04:23.432512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ec8b0c5811'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('course', sa.String(length=80), nullable=True))
    op.add_column('student', sa.Column('department', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'department')
    op.drop_column('student', 'course')
    # ### end Alembic commands ###
