"""empty message

Revision ID: 9ecee5e65df3
Revises: 1cab3aea5448
Create Date: 2022-05-08 05:42:15.009638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ecee5e65df3'
down_revision = '1cab3aea5448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'department')
    op.drop_column('student', 'course')
    op.drop_column('teachers', 'department')
    op.drop_column('teachers', 'course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('course', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('teachers', sa.Column('department', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('student', sa.Column('course', mysql.VARCHAR(length=80), nullable=True))
    op.add_column('student', sa.Column('department', mysql.VARCHAR(length=80), nullable=True))
    # ### end Alembic commands ###
